[conf_page]

[data]
samples = ['CEERs_DR0.7']
fluxes_log_path = 'data/tables/ceers_flux_log.txt'
files_log_path = 'data/tables/ceers_file_log.txt'

[tier1_v1.1]
folder = ''

[format]

[calibration]
factor = 4.2
k1 = 1
k2 = 1.2
k3 = 1.3
k4 = 3
logs = "CEERs_2022_data"
key = "89r3VTR7FGlffLPTkIRcGjI1x81_68NuD8of2AvmoOA="
norm = 1e-15

[theme]
base = "light"